/*Export Infra (résultat 'infra.sql' à injecter directement en SQL sur Pricer11)*/
SELECT * INTO OUTFILE 'c:/pricer/ftp/infra.sql' FROM (
SELECT
CASE
WHEN BSNAME = 'A' THEN (SELECT CONCAT ("REPLACE basestation (BSNAME, BSADDRESS) VALUES ('",BSNAME,"','pricerbs01');"))
WHEN BSNAME = 'B' THEN (SELECT CONCAT ("REPLACE basestation (BSNAME, BSADDRESS) VALUES ('",BSNAME,"','pricerbs02');"))
WHEN BSNAME = 'C' THEN (SELECT CONCAT ("REPLACE basestation (BSNAME, BSADDRESS) VALUES ('",BSNAME,"','pricerbs03');"))
WHEN BSNAME = 'D' THEN (SELECT CONCAT ("REPLACE basestation (BSNAME, BSADDRESS) VALUES ('",BSNAME,"','pricerbs04');"))
WHEN BSNAME = 'E' THEN (SELECT CONCAT ("REPLACE basestation (BSNAME, BSADDRESS) VALUES ('",BSNAME,"','pricerbs05');"))
END
FROM basestation
UNION ALL
SELECT CONCAT ("REPLACE subcell (SUBCELLID, SUBISBACKOFFICE, SUBCELLMODE, SUBBSNAME) VALUES ('",SUBCELLID,"','",SUBISBACKOFFICE,"','",SUBCELLMODE,"','",SUBBSNAME,"');") 
FROM subcell
UNION ALL
SELECT CONCAT ("REPLACE subcelltrxmap (TRXID, SCMSUBCELLID) VALUES ('",SCMTRXIDREF,"','",SCMSUBCELLID,"');") 
FROM subcelltrxmap
UNION ALL
SELECT CONCAT ("REPLACE transceiver (ID, TRXBSNAMEREF, TRXPORTNUM, TRXCABLEINDEX, TRXHWID) VALUES ('",TRXID,"','",TRXBSNAMEREF,"','",TRXPORTNUM,"','",TRXCABLEINDEX,"','",TRXHWID,"');") 
FROM transceiver
)I;


